using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace WorldOfTheThreeKingdoms.SourceGenerators;

/// <summary>
/// InfluenceKind 工厂源生成器
/// 🔥 扫描所有 InfluenceKind 派生类，生成静态工厂字典替代反射
/// 🔥 完全兼容 Native AOT，性能提升 10-100 倍
/// 🔥 2026-03-16：替代 InfluenceKindConverter 中的反射 API
/// </summary>
[Generator]
public class InfluenceKindFactoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 筛选所有继承自 InfluenceKind 的类
        var influenceKindClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: static (ctx, _) => GetInfluenceKindClass(ctx))
            .Where(static m => m is not null);

        // 2. 收集所有派生类
        var compilationAndClasses = context.CompilationProvider.Combine(influenceKindClasses.Collect());

        // 3. 生成代码
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    /// <summary>
    /// 语义分析：获取继承自 InfluenceKind 的类
    /// </summary>
    private static INamedTypeSymbol? GetInfluenceKindClass(GeneratorSyntaxContext context)
    {
        var classDecl = (Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (symbol is null)
            return null;

        // 检查是否继承自 InfluenceKind
        var baseType = symbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name == "InfluenceKind" && 
                baseType.ContainingNamespace.ToDisplayString() == "GameObjects.Influences")
            {
                return symbol;
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    /// <summary>
    /// 执行代码生成
    /// </summary>
    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
        {
            // 🔥 没有找到任何 InfluenceKind 派生类，生成空文件
            var emptySource = new StringBuilder();
            emptySource.AppendLine("// <auto-generated/>");
            emptySource.AppendLine("// ⚠️ 源生成器未找到任何 InfluenceKind 派生类");
            context.AddSource("InfluenceKindFactory.g.cs", emptySource.ToString());
            return;
        }

        // 🔥 调试日志
        var diagnosticLog = new StringBuilder();
        diagnosticLog.AppendLine($"[InfluenceKindFactoryGenerator] 开始生成 - {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        diagnosticLog.AppendLine($"[InfluenceKindFactoryGenerator] 找到 {classes.Length} 个 InfluenceKind 派生类");
        diagnosticLog.AppendLine();

        // 提取所有派生类的 ID（从类名中提取数字）
        var classInfos = classes
            .Select(c => new ClassInfoRecord(
                c,
                c.Name,
                ExtractIDFromClassName(c.Name) ?? -1
            ))
            .Where(c => c.ID >= 0)
            .OrderBy(c => c.ID)
            .ToList();

        diagnosticLog.AppendLine($"[InfluenceKindFactoryGenerator] 成功提取 {classInfos.Count} 个有效派生类");
        foreach (var info in classInfos)
        {
            diagnosticLog.AppendLine($"  ID={info.ID}, ClassName={info.ClassName}");
        }
        diagnosticLog.AppendLine();

        if (classInfos.Count == 0)
        {
            diagnosticLog.AppendLine("[InfluenceKindFactoryGenerator] ❌ 没有有效的派生类（无法从类名提取 ID）");
            var emptySource = new StringBuilder();
            emptySource.AppendLine("// <auto-generated/>");
            emptySource.AppendLine("/*");
            emptySource.Append(diagnosticLog.ToString());
            emptySource.AppendLine("*/");
            context.AddSource("InfluenceKindFactory.g.cs", emptySource.ToString());
            return;
        }

        diagnosticLog.AppendLine($"[InfluenceKindFactoryGenerator] ✅ 生成工厂字典，包含 {classInfos.Count} 个条目");
        diagnosticLog.AppendLine($"[InfluenceKindFactoryGenerator] 完成生成 - {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");

        // 生成代码
        var sourceCode = GenerateSource(classInfos, diagnosticLog.ToString());
        context.AddSource("InfluenceKindFactory.g.cs", sourceCode);
    }

    /// <summary>
    /// 从类名中提取 ID（如 InfluenceKind123 -> 123）
    /// </summary>
    private static int? ExtractIDFromClassName(string className)
    {
        if (!className.StartsWith("InfluenceKind"))
            return null;

        var numberPart = className.Substring("InfluenceKind".Length);
        if (int.TryParse(numberPart, out int id))
            return id;

        return null;
    }

    /// <summary>
    /// 类信息记录
    /// </summary>
    private sealed class ClassInfoRecord
    {
        public INamedTypeSymbol Symbol { get; }
        public string ClassName { get; }
        public int ID { get; }

        public ClassInfoRecord(INamedTypeSymbol symbol, string className, int id)
        {
            Symbol = symbol;
            ClassName = className;
            ID = id;
        }
    }

    /// <summary>
    /// 生成源代码
    /// </summary>
    private static string GenerateSource(System.Collections.Generic.List<ClassInfoRecord> classInfos, string debugLog)
    {
        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 🔥 InfluenceKind 工厂（自动生成）");
        sb.AppendLine("// 🔥 替代 InfluenceKindConverter 中的反射 API，完全兼容 Native AOT");
        sb.AppendLine("// 🔥 性能提升：10-100 倍");
        sb.AppendLine("// 🔥 2026-03-16：使用源生成器自动扫描所有派生类");
        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine("=== 源生成器调试日志 ===");
        sb.Append(debugLog);
        sb.AppendLine("*/");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using GameObjects.Influences;");
        sb.AppendLine("using GameObjects.Influences.InfluenceKindPack;");
        sb.AppendLine();
        sb.AppendLine("namespace WorldOfTheThreeKingdoms.Serialization.SystemTextJson;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// InfluenceKind 工厂（自动生成）");
        sb.AppendLine("/// 🔥 根据 ID 创建对应的派生类实例，无反射");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class InfluenceKindFactory");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 工厂字典：ID -> 创建函数");
        sb.AppendLine("    /// 🔥 使用 static lambda，避免闭包分配");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static readonly Dictionary<int, Func<InfluenceKind>> _registry = new()");
        sb.AppendLine("    {");

        // 生成工厂字典条目
        foreach (var info in classInfos)
        {
            int id = info.ID;
            string className = info.ClassName;
            sb.AppendLine($"        [{id}] = static () => new {className}(),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 根据 ID 创建 InfluenceKind 实例");
        sb.AppendLine("    /// 🔥 ANTI-BAND-AID：未知 ID 立即 Fail Fast");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static InfluenceKind Create(int id)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_registry.TryGetValue(id, out var factory))");
        sb.AppendLine("            return factory();");
        sb.AppendLine();
        sb.AppendLine("        // 🔥 ANTI-BAND-AID：数据损坏，立即抛出异常");
        sb.AppendLine("        throw new InvalidOperationException($\"数据损坏：未知的 InfluenceKind ID={id}\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
