// <auto-generated/>
// 🔥 属性访问器源生成器（AOT 兼容）
// 🔥 为实现 IPropertyAccessor 接口的类自动生成属性访问方法
// 🔥 日期：2026-03-16

#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace WorldOfTheThreeKingdoms.SourceGenerators;

/// <summary>
/// 属性访问器增量源生成器
/// 🔥 扫描实现 IPropertyAccessor 接口的 partial 类，生成 GetProperty/SetProperty/HasProperty 方法
/// 🔥 完全兼容 Native AOT，替代 MGSStartLoad 中的反射
/// 🔥 支持：属性（只读/读写）、字段（Field）
/// 🔥 大小写不敏感匹配
/// </summary>
[Generator]
public class PropertyAccessorGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IPropertyAccessor";
    private const string InterfaceFullName = "WorldOfTheThreeKingdoms.GameGlobal.IPropertyAccessor";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 筛选实现 IPropertyAccessor 接口的 partial 类
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        // 2. 收集所有需要生成的类信息
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // 3. 生成代码
        context.RegisterSourceOutput(compilationAndClasses, 
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    /// <summary>
    /// 快速筛选：是否是 partial 类声明
    /// </summary>
    private static bool IsCandidateClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl)
            return false;

        // 必须是 partial 类
        return classDecl.Modifiers.Any(m => m.ValueText == "partial");
    }

    /// <summary>
    /// 语义分析：获取实现 IPropertyAccessor 接口的类符号
    /// </summary>
    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (symbol is null)
            return null;

        // 检查是否实现 IPropertyAccessor 接口
        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.Name == InterfaceName || 
                iface.ToDisplayString() == InterfaceFullName)
            {
                return symbol;
            }
        }

        return null;
    }

    /// <summary>
    /// 执行代码生成
    /// </summary>
    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> classes, 
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        var diagnosticLog = new StringBuilder();
        diagnosticLog.AppendLine($"[PropertyAccessorGenerator] 开始生成");
        diagnosticLog.AppendLine($"[PropertyAccessorGenerator] 找到 {classes.Length} 个实现 IPropertyAccessor 的类");
        diagnosticLog.AppendLine();

        // 为每个类生成独立的文件
        foreach (var classSymbol in classes.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
        {
            diagnosticLog.AppendLine($"[生成类] {classSymbol.Name}");
            
            var classInfo = ExtractClassInfo(classSymbol, diagnosticLog);
            if (classInfo.Members.Count > 0)
            {
                var sourceCode = GenerateSource(classInfo, diagnosticLog.ToString());
                context.AddSource($"{classSymbol.Name}_PropertyAccessor.g.cs", sourceCode);
                diagnosticLog.AppendLine($"  ✅ 生成 {classInfo.Members.Count} 个成员的访问器");
            }
            else
            {
                diagnosticLog.AppendLine($"  ⚠️ 未找到任何可访问成员");
            }
            
            diagnosticLog.AppendLine();
        }

        diagnosticLog.AppendLine($"[PropertyAccessorGenerator] 完成生成");
    }

    /// <summary>
    /// 提取类的所有可访问成员（属性、字段）
    /// 🔥 递归扫描基类
    /// </summary>
    private static ClassInfo ExtractClassInfo(INamedTypeSymbol classSymbol, StringBuilder diagnosticLog)
    {
        List<MemberInfo> members = [];  // 🔥 C# 12 集合表达式
        HashSet<string> processedNames = new(StringComparer.OrdinalIgnoreCase);  // 🔥 C# 12 目标类型推断

        var currentType = classSymbol;
        int depth = 0;
        
        while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
        {
            diagnosticLog.AppendLine($"  [深度 {depth}] 扫描: {currentType.Name}");

            int propertyCount = 0, fieldCount = 0, skippedCount = 0;

            foreach (var member in currentType.GetMembers())
            {
                if (processedNames.Contains(member.Name))
                {
                    skippedCount++;
                    continue;
                }

                // 提取属性
                if (member is IPropertySymbol property &&
                    IsAccessible(property.DeclaredAccessibility) &&
                    !property.IsStatic &&
                    property.GetMethod != null)
                {
                    members.Add(new MemberInfo(
                        property.Name,
                        MemberKind.Property,
                        GetFullTypeName(property.Type),
                        property.SetMethod != null  // 是否可写
                    ));
                    processedNames.Add(property.Name);
                    propertyCount++;
                }
                // 提取字段
                else if (member is IFieldSymbol field &&
                    IsAccessible(field.DeclaredAccessibility) &&
                    !field.IsStatic &&
                    !field.IsImplicitlyDeclared &&
                    !field.IsConst)
                {
                    members.Add(new MemberInfo(
                        field.Name,
                        MemberKind.Field,
                        GetFullTypeName(field.Type),
                        !field.IsReadOnly  // 是否可写
                    ));
                    processedNames.Add(field.Name);
                    fieldCount++;
                }
            }

            diagnosticLog.AppendLine($"    提取: 属性={propertyCount}, 字段={fieldCount}, 跳过={skippedCount}");

            currentType = currentType.BaseType;
            depth++;
            
            if (depth > 20)
            {
                diagnosticLog.AppendLine($"    ⚠️ 达到最大扫描深度 (20)");
                break;
            }
        }

        return new ClassInfo(
            classSymbol.Name,
            GetFullTypeName(classSymbol),
            classSymbol.ContainingNamespace.ToDisplayString(),
            members
        );
    }

    /// <summary>
    /// 获取类型的完整限定名
    /// </summary>
    private static string GetFullTypeName(ITypeSymbol typeSymbol)
    {
        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    /// <summary>
    /// 判断成员是否可访问
    /// </summary>
    private static bool IsAccessible(Accessibility accessibility)
    {
        return accessibility == Accessibility.Public || accessibility == Accessibility.Internal;
    }

    /// <summary>
    /// 生成源代码
    /// </summary>
    private static string GenerateSource(ClassInfo classInfo, string debugLog)
    {
        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// 🔥 {classInfo.Name} 属性访问器（自动生成）");
        sb.AppendLine("// 🔥 实现 IPropertyAccessor 接口，替代反射");
        sb.AppendLine("// 🔥 日期：2026-03-16");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using WorldOfTheThreeKingdoms.GameGlobal;");
        sb.AppendLine();
        sb.AppendLine($"namespace {classInfo.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {classInfo.Name}");
        sb.AppendLine("{");

        // 生成 GetProperty 方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取属性值（自动生成）");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public object? GetProperty(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(name))");
        sb.AppendLine("            throw new ArgumentException(\"属性名不能为空\", nameof(name));");
        sb.AppendLine();
        sb.AppendLine("        string key = name.ToLowerInvariant();");
        sb.AppendLine();
        sb.AppendLine("        return key switch");
        sb.AppendLine("        {");

        // 生成所有属性的 get 分支
        foreach (var member in classInfo.Members)
        {
            string lowerName = member.Name.ToLowerInvariant();
            string accessor = member.Kind == MemberKind.Property ? member.Name : member.Name;
            sb.AppendLine($"            \"{lowerName}\" => {accessor},");
        }

        sb.AppendLine("            _ => throw new ArgumentException($\"未知属性: {name}\", nameof(name))");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成 SetProperty 方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 设置属性值（自动生成）");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void SetProperty(string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(name))");
        sb.AppendLine("            throw new ArgumentException(\"属性名不能为空\", nameof(name));");
        sb.AppendLine();
        sb.AppendLine("        string key = name.ToLowerInvariant();");
        sb.AppendLine();
        sb.AppendLine("        switch (key)");
        sb.AppendLine("        {");

        // 生成所有可写属性的 set 分支
        foreach (var member in classInfo.Members.Where(m => m.IsWritable))
        {
            string lowerName = member.Name.ToLowerInvariant();
            sb.AppendLine($"            case \"{lowerName}\":");
            sb.AppendLine($"                {member.Name} = ({member.TypeName})value!;");
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new ArgumentException($\"未知或只读属性: {name}\", nameof(name));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成 HasProperty 方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 检查属性是否存在（自动生成）");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool HasProperty(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(name))");
        sb.AppendLine("            return false;");
        sb.AppendLine();
        sb.AppendLine("        string key = name.ToLowerInvariant();");
        sb.AppendLine();
        sb.AppendLine("        return key switch");
        sb.AppendLine("        {");

        // 生成所有属性的存在性检查
        foreach (var member in classInfo.Members)
        {
            string lowerName = member.Name.ToLowerInvariant();
            sb.AppendLine($"            \"{lowerName}\" => true,");
        }

        sb.AppendLine("            _ => false");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 类信息
    /// </summary>
    private class ClassInfo
    {
        public string Name { get; }
        public string FullyQualifiedName { get; }
        public string Namespace { get; }
        public List<MemberInfo> Members { get; }

        public ClassInfo(string name, string fullyQualifiedName, string ns, List<MemberInfo> members)
        {
            Name = name;
            FullyQualifiedName = fullyQualifiedName;
            Namespace = ns;
            Members = members;
        }
    }

    /// <summary>
    /// 成员信息
    /// </summary>
    private class MemberInfo
    {
        public string Name { get; }
        public MemberKind Kind { get; }
        public string TypeName { get; }
        public bool IsWritable { get; }

        public MemberInfo(string name, MemberKind kind, string typeName, bool isWritable)
        {
            Name = name;
            Kind = kind;
            TypeName = typeName;
            IsWritable = isWritable;
        }
    }

    /// <summary>
    /// 成员类型
    /// </summary>
    private enum MemberKind
    {
        Property,
        Field
    }
}
