using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace WorldOfTheThreeKingdoms.SourceGenerators
{
    /// <summary>
    /// Source Generator: Generate texture assignment code for ArchitectureDetailPlugin
    /// Replaces reflection to comply with AOT requirements
    /// </summary>
    [Generator]
    public class TextureAssignmentGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // No syntax receiver needed - we generate static code
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Generate the complete texture assignment code
            var source = GenerateCompleteAssignmentCode();

            // Add generated source
            context.AddSource("ArchitectureDetailPlugin.TextureAssignment.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private string GenerateCompleteAssignmentCode()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file is generated by Source Generator - DO NOT EDIT");
            sb.AppendLine("// Generator: TextureAssignmentGenerator");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.Xna.Framework.Graphics;");
            sb.AppendLine("using GameManager;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Xml;");
            sb.AppendLine();
            sb.AppendLine("namespace ArchitectureDetail");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class ArchitectureDetailPlugin");
            sb.AppendLine("    {");

            // Generate bar texture assignments
            GenerateBarTextureMethod(sb);

            // Generate page background assignments
            GeneratePageBackgroundMethod(sb);

            // Generate button texture assignments
            GenerateButtonTextureMethod(sb);

            // Generate facility texture assignments
            GenerateFacilityTextureMethod(sb);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void GenerateBarTextureMethod(StringBuilder sb)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Assign bar textures (Generated by Source Generator)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private void AssignBarTexturesGenerated(Dictionary<string, Texture2D> textures, XmlNode nextSibling)");
            sb.AppendLine("        {");
            sb.AppendLine("            string basePath = @\"Content\\Textures\\GameComponents\\ArchitectureDetail\\Data\\Backgrounds\\Bar\\\";");
            sb.AppendLine();

            // Integration (node 26)
            sb.AppendLine("            // Integration (node 26)");
            sb.AppendLine("            XmlNode node = nextSibling.ChildNodes.Item(26);");
            for (int i = 0; i < 6; i++)
            {
                sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"FileName{i}\").Value, out var integration{i}Texture))");
                sb.AppendLine($"                this.architectureDetail.Integration{i + 1}BarTexture = new PlatformTexture(integration{i}Texture);");
            }
            sb.AppendLine();

            // Other bar types
            var barTypes = new[] { 
                ("Domination", 27), ("Endurance", 28), ("Agriculture", 29), 
                ("Commerce", 30), ("Technology", 31), ("Morale", 32), ("FacilityCount", 33) 
            };

            foreach (var (barType, nodeIndex) in barTypes)
            {
                sb.AppendLine($"            // {barType} (node {nodeIndex})");
                sb.AppendLine($"            node = nextSibling.ChildNodes.Item({nodeIndex});");
                for (int i = 0; i < 6; i++)
                {
                    var varName = barType.ToLower() + i;
                    sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"FileName{i}\").Value, out var {varName}Texture))");
                    sb.AppendLine($"                this.architectureDetail.{barType}{i + 1}BarTexture = new PlatformTexture({varName}Texture);");
                }
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GeneratePageBackgroundMethod(StringBuilder sb)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Assign page background textures (Generated by Source Generator)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private void AssignPageBackgroundsGenerated(Dictionary<string, Texture2D> textures, XmlNode nextSibling)");
            sb.AppendLine("        {");
            sb.AppendLine("            XmlNode node = nextSibling.ChildNodes.Item(203);");
            sb.AppendLine("            string basePath = @\"Content\\Textures\\GameComponents\\ArchitectureDetail\\Data\\TheFacilityPage\\Background\\\";");
            sb.AppendLine();

            // Generate 30 page backgrounds
            for (int i = 1; i <= 30; i++)
            {
                sb.AppendLine($"            // Mask{i} & Background{i}");
                sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"Mask{i}\").Value, out var mask{i}Texture))");
                sb.AppendLine($"                this.architectureDetail.PageForFacilityMask{i} = new PlatformTexture(mask{i}Texture);");
                sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"Background{i}\").Value, out var bg{i}Texture))");
                sb.AppendLine($"                this.architectureDetail.PageForFacilityBackground{i} = new PlatformTexture(bg{i}Texture);");
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GenerateButtonTextureMethod(StringBuilder sb)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Assign button textures (Generated by Source Generator)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private void AssignButtonTexturesGenerated(Dictionary<string, Texture2D> textures, XmlNode nextSibling)");
            sb.AppendLine("        {");
            sb.AppendLine("            string basePath = @\"Content\\Textures\\GameComponents\\ArchitectureDetail\\Data\\TheFacilityPage\\Button\\\";");
            sb.AppendLine("            XmlNode node;");
            sb.AppendLine();

            // Generate 30 button textures
            for (int i = 1; i <= 30; i++)
            {
                int nodeIndex = 205 + i;
                sb.AppendLine($"            // FacilityforPage{i} (node {nodeIndex})");
                sb.AppendLine($"            node = nextSibling.ChildNodes.Item({nodeIndex});");
                sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"FileName\").Value, out var btn{i}Texture))");
                sb.AppendLine($"                this.architectureDetail.FacilityforPage{i}ButtonTexture = new PlatformTexture(btn{i}Texture);");
                sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"PressedName\").Value, out var btnPressed{i}Texture))");
                sb.AppendLine($"                this.architectureDetail.FacilityforPage{i}PressedTexture = new PlatformTexture(btnPressed{i}Texture);");
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GenerateFacilityTextureMethod(StringBuilder sb)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Assign facility textures (Generated by Source Generator)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private void AssignFacilityTexturesGenerated(Dictionary<string, Texture2D> textures, XmlNode nextSibling)");
            sb.AppendLine("        {");
            sb.AppendLine("            string basePath = @\"Content\\Textures\\GameComponents\\ArchitectureDetail\\Data\\TheFacilityPage\\Facility\\\";");
            sb.AppendLine("            XmlNode node;");
            sb.AppendLine();

            // Generate 200 facility textures
            for (int i = 1; i <= 200; i++)
            {
                int nodeIndex = 600 + i;
                sb.AppendLine($"            // Facility{i} (node {nodeIndex})");
                sb.AppendLine($"            node = nextSibling.ChildNodes.Item({nodeIndex});");
                sb.AppendLine($"            if (textures.TryGetValue(basePath + node.Attributes.GetNamedItem(\"Picture\").Value, out var facility{i}Texture))");
                sb.AppendLine($"                this.architectureDetail.Facility{i}TextPicture = new PlatformTexture(facility{i}Texture);");
                sb.AppendLine();
            }

            sb.AppendLine("        }");
        }
    }
}
