using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace WorldOfTheThreeKingdoms.SourceGenerators;

/// <summary>
/// UI 属性访问器增量源生成器（完全重构版）
/// 🔥 扫描带有 [GenerateUIAccessor] 特性的类，生成静态路由方法替代反射
/// 🔥 完全兼容 Native AOT，性能提升 10-100 倍
/// 🔥 支持：属性（只读/读写）、字段（Field）、无参方法
/// 🔥 大小写不敏感匹配（兼容旧 XML 配置）
/// </summary>
[Generator]
public class UIPropertyAccessorGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GenerateUIAccessorAttribute";
    private const string AttributeFullName = "GameGlobal.GenerateUIAccessorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 筛选带有 [GenerateUIAccessor] 特性的类声明
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        // 2. 收集所有需要生成的类信息
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // 3. 生成代码
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    /// <summary>
    /// 快速筛选：是否是类声明
    /// </summary>
    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl && classDecl.AttributeLists.Count > 0;
    }

    /// <summary>
    /// 语义分析：获取带有 [GenerateUIAccessor] 特性的类符号
    /// </summary>
    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is null)
            return null;

        // 检查是否有 [GenerateUIAccessor] 特性
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == AttributeName ||
                attr.AttributeClass?.ToDisplayString() == AttributeFullName)
            {
                return symbol;
            }
        }

        return null;
    }

    /// <summary>
    /// 执行代码生成
    /// </summary>
    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        // 🔥 调试日志：开始生成
        var diagnosticLog = new StringBuilder();
        diagnosticLog.AppendLine($"[UIPropertyAccessorGenerator] 开始生成 - {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        diagnosticLog.AppendLine($"[UIPropertyAccessorGenerator] 找到 {classes.Length} 个带 [GenerateUIAccessor] 特性的类");
        diagnosticLog.AppendLine();

        // 收集所有类的成员信息
        List<ClassInfo> classInfos = [];  // 🔥 C# 12 集合表达式
        int totalMemberCount = 0;

        foreach (var classSymbol in classes.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
        {
            diagnosticLog.AppendLine($"[扫描类] {classSymbol.Name} ({classSymbol.ToDisplayString()})");
            
            var classInfo = ExtractClassInfo(classSymbol, diagnosticLog);
            if (classInfo.Members.Count > 0)
            {
                classInfos.Add(classInfo);
                totalMemberCount += classInfo.Members.Count;
                diagnosticLog.AppendLine($"  ✅ 成功提取 {classInfo.Members.Count} 个成员");
            }
            else
            {
                diagnosticLog.AppendLine($"  ⚠️ 未找到任何可访问成员");
                
                // 🔥 报告警告：类没有可访问成员
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "UIPROP001",
                        "源生成器未找到可访问成员",
                        "类 '{0}' 标记了 [GenerateUIAccessor]，但未找到任何可访问的属性、字段或方法",
                        "SourceGenerator",
                        DiagnosticSeverity.Warning,
                        isEnabledByDefault: true),
                    Location.None,
                    classSymbol.Name));
            }
            
            diagnosticLog.AppendLine();
        }

        if (classInfos.Count == 0)
        {
            diagnosticLog.AppendLine("[UIPropertyAccessorGenerator] ❌ 没有生成任何代码（所有类都没有可访问成员）");
            
            // 🔥 输出调试日志作为注释嵌入到空文件中
            var emptySource = new StringBuilder();
            emptySource.AppendLine("// <auto-generated/>");
            emptySource.AppendLine("// 🔥 源生成器调试日志");
            emptySource.AppendLine("/*");
            emptySource.Append(diagnosticLog.ToString());
            emptySource.AppendLine("*/");
            
            context.AddSource("UIPropertyAccessor.g.cs", emptySource.ToString());
            return;
        }

        diagnosticLog.AppendLine($"[UIPropertyAccessorGenerator] ✅ 共生成 {classInfos.Count} 个类的访问器，包含 {totalMemberCount} 个成员");
        diagnosticLog.AppendLine($"[UIPropertyAccessorGenerator] 完成生成 - {DateTime.Now:yyyy-MM-dd HH:mm:ss}");

        // 生成代码
        var sourceCode = GenerateSource(classInfos, diagnosticLog.ToString());
        context.AddSource("UIPropertyAccessor.g.cs", sourceCode);
    }

    /// <summary>
    /// 提取类的所有可访问成员（属性、字段、方法）
    /// 🔥 递归扫描基类，直到 System.Object
    /// 🔥 使用 global:: 全局限定名，彻底杜绝命名空间匹配失败
    /// 🔥 2026-03-04 修复：添加诊断输出，追踪扫描过程
    /// 🔥 2026-03-06 增强：详细的调试日志和错误报告
    /// </summary>
    private static ClassInfo ExtractClassInfo(INamedTypeSymbol classSymbol, StringBuilder diagnosticLog)
    {
        List<MemberInfo> members = [];  // 🔥 C# 12 集合表达式
        HashSet<string> processedNames = new(StringComparer.OrdinalIgnoreCase);  // 避免重复（子类覆盖）

        // 🔥 递归扫描类及其所有基类
        var currentType = classSymbol;
        int depth = 0;
        while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
        {
            var allMembers = currentType.GetMembers();
            diagnosticLog.AppendLine($"  [深度 {depth}] 扫描类型: {currentType.Name} (成员数: {allMembers.Length})");

            int propertyCount = 0, fieldCount = 0, methodCount = 0, methodWithParamCount = 0, skippedCount = 0;

            foreach (var member in allMembers)
            {
                // 跳过已处理的成员（子类覆盖优先）
                if (processedNames.Contains(member.Name))
                {
                    skippedCount++;
                    continue;
                }

                // 🔥 1. 提取属性（Property）- 包括只读属性
                if (member is IPropertySymbol property &&
                    IsAccessible(property.DeclaredAccessibility) &&
                    !property.IsStatic &&
                    property.GetMethod != null)  // 必须有 get 访问器
                {
                    members.Add(new MemberInfo(
                        property.Name,
                        MemberKind.Property,
                        GetFullTypeName(property.Type),
                        property.Type.IsValueType,
                        IsBoolType(property.Type),
                        []  // 无参数
                    ));
                    processedNames.Add(property.Name);
                    propertyCount++;
                }

                // 🔥 2. 提取字段（Field）- 包括 public 和 internal
                else if (member is IFieldSymbol field &&
                    IsAccessible(field.DeclaredAccessibility) &&
                    !field.IsStatic &&
                    !field.IsImplicitlyDeclared &&  // 排除编译器生成的字段
                    !field.IsConst)  // 排除常量
                {
                    members.Add(new MemberInfo(
                        field.Name,
                        MemberKind.Field,
                        GetFullTypeName(field.Type),
                        field.Type.IsValueType,
                        IsBoolType(field.Type),
                        []  // 无参数
                    ));
                    processedNames.Add(field.Name);
                    fieldCount++;
                }

                // 🔥 3. 提取方法（Method）- 无参且有返回值
                else if (member is IMethodSymbol method &&
                    IsAccessible(method.DeclaredAccessibility) &&
                    !method.IsStatic &&
                    method.MethodKind == MethodKind.Ordinary &&
                    method.Parameters.Length == 0 &&
                    !method.ReturnsVoid)
                {
                    members.Add(new MemberInfo(
                        method.Name,
                        MemberKind.Method,
                        GetFullTypeName(method.ReturnType),
                        method.ReturnType.IsValueType,
                        IsBoolType(method.ReturnType),
                        []  // 无参数
                    ));
                    processedNames.Add(method.Name);
                    methodCount++;
                }
                
                // 🔥 4. 提取带一个 int 参数的方法（用于 UI 按钮可用性判断）
                else if (member is IMethodSymbol methodWithParam &&
                    IsAccessible(methodWithParam.DeclaredAccessibility) &&
                    !methodWithParam.IsStatic &&
                    methodWithParam.MethodKind == MethodKind.Ordinary &&
                    methodWithParam.Parameters.Length == 1 &&
                    methodWithParam.Parameters[0].Type.SpecialType == SpecialType.System_Int32 &&
                    !methodWithParam.ReturnsVoid)
                {
                    members.Add(new MemberInfo(
                        methodWithParam.Name,
                        MemberKind.MethodWithIntParam,
                        GetFullTypeName(methodWithParam.ReturnType),
                        methodWithParam.ReturnType.IsValueType,
                        IsBoolType(methodWithParam.ReturnType),
                        [("id", "int")]  // 一个 int 参数
                    ));
                    processedNames.Add(methodWithParam.Name);
                    methodWithParamCount++;
                }
            }

            diagnosticLog.AppendLine($"    提取: 属性={propertyCount}, 字段={fieldCount}, 无参方法={methodCount}, 带参方法={methodWithParamCount}, 跳过={skippedCount}");

            // 移动到基类
            currentType = currentType.BaseType;
            depth++;
            
            // 🔥 安全限制：防止无限循环
            if (depth > 20)
            {
                diagnosticLog.AppendLine($"    ⚠️ 达到最大扫描深度 (20)，停止扫描");
                break;
            }
        }

        diagnosticLog.AppendLine($"  总计提取: {members.Count} 个成员");

        return new ClassInfo(
            classSymbol.Name,
            GetFullTypeName(classSymbol),
            members
        );
    }

    /// <summary>
    /// 获取类型的完整限定名（带 global:: 前缀）
    /// 🔥 彻底杜绝命名空间匹配失败
    /// </summary>
    private static string GetFullTypeName(ITypeSymbol typeSymbol)
    {
        var fullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        
        // 确保以 global:: 开头
        if (!fullName.StartsWith("global::"))
        {
            fullName = "global::" + fullName;
        }
        
        return fullName;
    }

    /// <summary>
    /// 判断类型是否为 bool
    /// </summary>
    private static bool IsBoolType(ITypeSymbol typeSymbol)
    {
        return typeSymbol.SpecialType == SpecialType.System_Boolean;
    }

    /// <summary>
    /// 判断成员是否可访问（public 或 internal）
    /// </summary>
    private static bool IsAccessible(Accessibility accessibility)
    {
        return accessibility == Accessibility.Public || accessibility == Accessibility.Internal;
    }

    /// <summary>
    /// 生成源代码
    /// 🔥 修复：使用 Dictionary 查找表，O(1) 性能 + 彻底避免 CS0152
    /// 🔥 2026-03-04 修复：正确生成带参数方法的调用代码
    /// 🔥 2026-03-04 修复：使用特殊哨兵对象，避免与属性返回的 "----" 混淆
    /// 🔥 2026-03-06 增强：嵌入调试日志作为注释
    /// </summary>
    private static string GenerateSource(List<ClassInfo> classInfos, string debugLog)
    {
        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 🔥 UI 属性访问器（自动生成）");
        sb.AppendLine("// 🔥 替代 StaticMethods 中的反射方法，完全兼容 Native AOT");
        sb.AppendLine("// 🔥 性能提升：10-100 倍");
        sb.AppendLine("// 🔥 支持：属性（只读/读写）、字段（Field）、无参方法、带 int 参数的方法");
        sb.AppendLine("// 🔥 大小写不敏感匹配（兼容旧 XML 配置）");
        sb.AppendLine("// 🔥 2026-03-04：使用特殊哨兵对象，精确识别属性/方法不存在");
        sb.AppendLine("// 🔥 2026-03-06：添加调试日志和错误报告");
        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine("=== 源生成器调试日志 ===");
        sb.Append(debugLog);
        sb.AppendLine("*/");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace GameGlobal;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// UI 属性访问器（自动生成）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class UIPropertyAccessor");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 特殊哨兵对象：表示属性/方法不存在");
        sb.AppendLine("    /// 🔥 使用对象引用而非字符串，避免与属性返回的 \"----\" 混淆");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static readonly object PropertyNotFoundSentinel = new();");
        sb.AppendLine();

        // 为每个类生成专用的访问方法
        foreach (var classInfo in classInfos)
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// 获取 {classInfo.Name} 的成员值");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    private static object? Get_{classInfo.Name}_Value({classInfo.FullyQualifiedName} obj, string key)");
            sb.AppendLine("    {");
            
            // 🔥 特殊处理：Person 类的五维属性（手动补充，因为自动扫描可能遗漏）
            if (classInfo.Name == "Person")
            {
                sb.AppendLine("        // 🔥 Normal* 五维属性（XML 配置使用的属性名）");
                sb.AppendLine("        if (key == \"normalstrength\")");
                sb.AppendLine("            return obj.NormalStrength;");
                sb.AppendLine("        else if (key == \"normalcommand\")");
                sb.AppendLine("            return obj.NormalCommand;");
                sb.AppendLine("        else if (key == \"normalintelligence\")");
                sb.AppendLine("            return obj.NormalIntelligence;");
                sb.AppendLine("        else if (key == \"normalpolitics\")");
                sb.AppendLine("            return obj.NormalPolitics;");
                sb.AppendLine("        else if (key == \"normalglamour\")");
                sb.AppendLine("            return obj.NormalGlamour;");
                sb.AppendLine();
                sb.AppendLine("        // 🔥 五维属性（兼容旧配置）");
                sb.AppendLine("        else if (key == \"strength\")");
                sb.AppendLine("            return obj.Strength;");
                sb.AppendLine("        else if (key == \"command\")");
                sb.AppendLine("            return obj.Command;");
                sb.AppendLine("        else if (key == \"intelligence\")");
                sb.AppendLine("            return obj.Intelligence;");
                sb.AppendLine("        else if (key == \"politics\")");
                sb.AppendLine("            return obj.Politics;");
                sb.AppendLine("        else if (key == \"glamour\")");
                sb.AppendLine("            return obj.Glamour;");
                sb.AppendLine();
                sb.AppendLine("        // 🔥 五维经验值");
                sb.AppendLine("        else if (key == \"strengthexperience\")");
                sb.AppendLine("            return obj.StrengthExperience;");
                sb.AppendLine("        else if (key == \"commandexperience\")");
                sb.AppendLine("            return obj.CommandExperience;");
                sb.AppendLine("        else if (key == \"intelligenceexperience\")");
                sb.AppendLine("            return obj.IntelligenceExperience;");
                sb.AppendLine("        else if (key == \"politicsexperience\")");
                sb.AppendLine("            return obj.PoliticsExperience;");
                sb.AppendLine("        else if (key == \"glamourexperience\")");
                sb.AppendLine("            return obj.GlamourExperience;");
                sb.AppendLine();
                sb.AppendLine("        // 🔥 五维升级所需经验");
                sb.AppendLine("        else if (key == \"strengthlevelupneedexp\")");
                sb.AppendLine("            return obj.StrengthLevelUpNeedExp;");
                sb.AppendLine("        else if (key == \"commandlevelupneedexp\")");
                sb.AppendLine("            return obj.CommandLevelUpNeedExp;");
                sb.AppendLine("        else if (key == \"intelligencelevelupneedexp\")");
                sb.AppendLine("            return obj.IntelligenceLevelUpNeedExp;");
                sb.AppendLine("        else if (key == \"politicslevelupneedexp\")");
                sb.AppendLine("            return obj.PoliticsLevelUpNeedExp;");
                sb.AppendLine("        else if (key == \"glamourlevelupneedexp\")");
                sb.AppendLine("            return obj.GlamourLevelUpNeedExp;");
                sb.AppendLine();
            }

            // 🔥 强力去重：使用 HashSet 防止重复成员
            HashSet<string> uniqueKeys = new(StringComparer.OrdinalIgnoreCase);
            List<(string key, string expression)> validMembers = [];

            foreach (var member in classInfo.Members)
            {
                string lowerName = member.Name.ToLowerInvariant();

                // 🔥 如果已存在，直接跳过（彻底杜绝重复）
                if (!uniqueKeys.Add(lowerName))
                {
                    continue;
                }

                string? accessor = member.Kind switch
                {
                    MemberKind.Property => $"obj.{member.Name}",
                    MemberKind.Field => $"obj.{member.Name}",
                    MemberKind.Method => $"obj.{member.Name}()",
                    MemberKind.MethodWithIntParam => null,  // 带参数的方法单独处理
                    _ => throw new InvalidOperationException($"Unknown member kind: {member.Kind}")
                };
                
                // 🔥 跳过带参数的方法（它们会在单独的方法中处理）
                if (accessor == null)
                    continue;

                // 🔥 bool 类型直接返回，不转换为字符串（性能优化 + 类型安全）
                // 🔥 int 类型直接返回（装箱为 object），避免 ToString() 分配
                // 🔥 其他值类型调用 ToString()
                // 🔥 引用类型需要 null 检查（游戏逻辑中的合法 null，如 Person.Faction）
                string expression;
                if (member.IsBool)
                {
                    // bool 类型直接返回（装箱为 object）- 避免 InvalidCastException
                    expression = accessor;
                }
                else if (member.TypeName == "global::System.Int32" || 
                         member.TypeName == "global::System.Int64" ||
                         member.TypeName == "global::System.Single" ||
                         member.TypeName == "global::System.Double")
                {
                    // 数值类型直接返回（装箱为 object）- 避免 ToString() 分配
                    expression = accessor;
                }
                else if (member.IsValueType)
                {
                    // 其他值类型转换为字符串
                    expression = $"{accessor}.ToString()";
                }
                else
                {
                    // 引用类型需要 null 检查
                    expression = $"{accessor}?.ToString() ?? \"----\"";
                }

                validMembers.Add((lowerName, expression));
            }

            // 生成 if-else 链（每个类的成员数量有限，性能可接受）
            if (validMembers.Count > 0)
            {
                for (int i = 0; i < validMembers.Count; i++)
                {
                    var (key, expr) = validMembers[i];
                    string ifKeyword = i == 0 ? "if" : "else if";
                    sb.AppendLine($"        {ifKeyword} (key == \"{key}\")");
                    sb.AppendLine($"            return {expr};");
                }
            }

            sb.AppendLine("        return PropertyNotFoundSentinel;  // 🔥 返回哨兵对象，而非 \"----\"");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // 生成主方法（类型分发）
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取对象成员值（生成版本，替代反射）");
        sb.AppendLine("    /// 🔥 大小写不敏感匹配（兼容旧 XML 配置）");
        sb.AppendLine("    /// 🔥 支持：属性、字段、无参方法");
        sb.AppendLine("    /// 🔥 返回 PropertyNotFoundSentinel 表示成员不存在");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static object? GetPropertyValueGenerated(object? instance, string memberName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (instance == null || string.IsNullOrEmpty(memberName))");
        sb.AppendLine("            return PropertyNotFoundSentinel;");
        sb.AppendLine();
        sb.AppendLine("        // 🔥 转为小写，实现大小写不敏感匹配");
        sb.AppendLine("        string key = memberName.ToLowerInvariant();");
        sb.AppendLine();
        sb.AppendLine("        // 🔥 类型分发（使用 switch 表达式，O(1) 性能）");
        sb.AppendLine("        return instance switch");
        sb.AppendLine("        {");

        // 为每个类生成 switch case（调用专用方法）
        foreach (var classInfo in classInfos)
        {
            sb.AppendLine($"            {classInfo.FullyQualifiedName} obj => Get_{classInfo.Name}_Value(obj, key),");
        }

        sb.AppendLine("            _ => PropertyNotFoundSentinel");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // 🔥 新增：生成带一个 int 参数的方法访问器
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 调用带一个 int 参数的方法（生成版本，替代反射）");
        sb.AppendLine("    /// 🔥 用于 UI 按钮可用性判断（如 HasStratagem(int id)）");
        sb.AppendLine("    /// 🔥 2026-03-04 修复：正确生成所有类的方法调用");
        sb.AppendLine("    /// 🔥 返回 PropertyNotFoundSentinel 表示方法不存在");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static object? CallMethodWithIntParam(object? instance, string methodName, int param)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (instance == null || string.IsNullOrEmpty(methodName))");
        sb.AppendLine("            return PropertyNotFoundSentinel;");
        sb.AppendLine();
        sb.AppendLine("        // 🔥 转为小写，实现大小写不敏感匹配");
        sb.AppendLine("        string key = methodName.ToLowerInvariant();");
        sb.AppendLine();
        
        // 🔥 修复：为每个类生成带参数方法的调用（使用正确的变量名）
        bool hasAnyMethod = false;
        foreach (var classInfo in classInfos)
        {
            // 筛选出带 int 参数的方法
            var methodsWithIntParam = classInfo.Members
                .Where(m => m.Kind == MemberKind.MethodWithIntParam)
                .ToList();
            
            if (methodsWithIntParam.Count > 0)
            {
                hasAnyMethod = true;
                string varName = $"obj{classInfo.Name}";  // 🔥 使用唯一的变量名
                
                sb.AppendLine($"        // 🔥 {classInfo.Name} 类的带参数方法");
                sb.AppendLine($"        if (instance is {classInfo.FullyQualifiedName} {varName})");
                sb.AppendLine("        {");
                
                for (int i = 0; i < methodsWithIntParam.Count; i++)
                {
                    var method = methodsWithIntParam[i];
                    string lowerName = method.Name.ToLowerInvariant();
                    string ifKeyword = i == 0 ? "if" : "else if";
                    
                    sb.AppendLine($"            {ifKeyword} (key == \"{lowerName}\")");
                    sb.AppendLine($"                return {varName}.{method.Name}(param);");
                }
                
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }
        
        if (!hasAnyMethod)
        {
            sb.AppendLine("        // 🔥 暂无带 int 参数的方法");
        }
        
        sb.AppendLine("        return PropertyNotFoundSentinel;  // 🔥 返回哨兵对象");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 类信息（C# 12 主构造函数）
    /// </summary>
    private class ClassInfo(string name, string fullyQualifiedName, List<MemberInfo> members)
    {
        public string Name { get; } = name;
        public string FullyQualifiedName { get; } = fullyQualifiedName;
        public List<MemberInfo> Members { get; } = members;
    }

    /// <summary>
    /// 成员信息（C# 12 主构造函数）
    /// </summary>
    private class MemberInfo(string name, MemberKind kind, string typeName, bool isValueType, bool isBool, List<(string name, string type)> parameters)
    {
        public string Name { get; } = name;
        public MemberKind Kind { get; } = kind;
        public string TypeName { get; } = typeName;
        public bool IsValueType { get; } = isValueType;
        public bool IsBool { get; } = isBool;
        public List<(string name, string type)> Parameters { get; } = parameters;
    }

    /// <summary>
    /// 成员类型
    /// </summary>
    private enum MemberKind
    {
        Property,
        Field,
        Method,
        MethodWithIntParam  // 🔥 新增：带一个 int 参数的方法
    }
}
