// <auto-generated/>
// 🔥 动态属性访问接口（AOT 兼容）
// 🔥 用于替代 MGSStartLoad 中的反射属性访问
// 🔥 日期：2026-03-16

#nullable disable

namespace WorldOfTheThreeKingdoms.GameGlobal;

/// <summary>
/// 动态属性访问接口（AOT 兼容）
/// 🔥 用于替代反射的属性访问
/// 🔥 实现类需标记为 partial，源生成器会自动生成实现
/// </summary>
public interface IPropertyAccessor
{
    /// <summary>
    /// 获取属性值
    /// </summary>
    /// <param name="name">属性名（大小写不敏感）</param>
    /// <returns>属性值，如果属性不存在则抛出 ArgumentException</returns>
    object? GetProperty(string name);

    /// <summary>
    /// 设置属性值
    /// </summary>
    /// <param name="name">属性名（大小写不敏感）</param>
    /// <param name="value">属性值</param>
    /// <exception cref="ArgumentException">属性不存在或只读</exception>
    void SetProperty(string name, object? value);

    /// <summary>
    /// 检查属性是否存在
    /// </summary>
    /// <param name="name">属性名（大小写不敏感）</param>
    /// <returns>true 表示属性存在</returns>
    bool HasProperty(string name);
}
