using Microsoft.Xna.Framework;

namespace GameObjects.AI;

public sealed record FactionIntent(
    FactionIntentId Id,
    FactionIntentKind Kind,
    int Priority,
    int CommitUntilTick,
    int SourceFactionId,
    int StrategicFocusArchitectureId,
    Point StrategicFocusPosition,
    int StrategicFocusScore,
    int DefensiveFocusArchitectureId,
    Point DefensiveFocusPosition,
    int DefensiveFocusScore,
    int TheaterVisibilityConfidence,
    int TheaterEnergyBalance,
    FactionStrategyMode StrategyMode,
    int StrategyCommitUntilTick,
    int StrategyReevaluateAfterTick,
    int SecondaryFocusArchitectureId,
    Point SecondaryFocusPosition,
    int SecondaryFocusScore,
    int ReserveRatioPermille,
    int SortieBudgetPermille,
    int SiegeBudgetPermille,
    int StrategyRiskTolerance,
    bool AttackFrozen,
    int StrategyPressure,
    int FailurePressure,
    int ThreatPressure,
    int PersonalityAggressionPermille,
    int PersonalityDefensePermille,
    int PersonalityRiskPermille,
    int PersonalityDisciplinePermille,
    int PersonalityVolatilityPermille)
{
    public static FactionIntent CreateHold(int factionId, int issuedTick)
    {
        return new FactionIntent(
            new FactionIntentId(factionId, 1, issuedTick),
            FactionIntentKind.Hold,
            0,
            issuedTick,
            factionId,
            -1,
            Point.Zero,
            0,
            -1,
            Point.Zero,
            0,
            0,
            0,
            FactionStrategyMode.Rest,
            issuedTick + 1,
            issuedTick + 1,
            -1,
            Point.Zero,
            0,
            700,
            200,
            100,
            40,
            true,
            0,
            0,
            0,
            1000,
            1000,
            1000,
            1000,
            900);
    }
}
